= dmenu-websearch
ifndef::env-github[:icons: font]
ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:experimental:

Shorthand for web search based on each own query with dmenu.

== 📦 Dependencies

. link:https://tools.suckless.org/dmenu/[dmenu^] is a dynamic menu for X
. link:https://github.com/stedolan/jq[jq^] is a lightweight and flexible command-line JSON processor

== 🌎 Web Search Queries

[source,bash,linenums]
----
OPTIONS='''
[
[ "Arch:Manpage",        "https://man.archlinux.org/search?q=" ],
[ "Arch:Wiki",           "https://wiki.archlinux.org/index.php?search=" ],
[ "Arch:Packages",       "https://archlinux.org/packages/?q=" ],
[ "Arch:Packages:AUR",   "https://aur.archlinux.org/packages/?K=" ],
[ "DuckDuckGo:Search",   "https://duckduckgo.com/?q=" ],
[ "GitHub:Search",       "https://github.com/search?q=" ],
[ "Google:Search",       "https://duckduckgo.com/?q=!g+" ],
[ "Google:Search:Image", "https://duckduckgo.com/?q=!gi+" ],
[ "Google:Translate",    "https://translate.google.com/?sl=auto&tl=id&text=" ],
[ "Ruby:Gems",           "https://rubygems.org/gems/" ],
[ "Ruby:Toolbox",        "https://www.ruby-toolbox.com/search?q=" ]
]
'''
----

== 🏗️  How to add new queriey?

Just add in the `OPTIONS` array.

IMPORTANT: *Don't give comma `,` in the last element!*

== 🍱 How to use?

Complete the *menu search* with kbd:[Tab], and write down your keywords.

The form should be like this,

----
Prefix:Menu <your> <keywords>
----

NOTE: You're free to define the *prefix menu*. My example is just for ease in explaining.

== 🍻 Related Project

. link:https://github.com/m0rphism/haskell-dmenu-search[haskell-dmenu-search^], dmenu script for searching the web with customizable search engines.

== 🏛️ Copyright and License

Copyright © 2021 Rizqi Nur Assyaufi. Free use of this software is granted under the terms of the MIT License. See link:https://raw.githubusercontent.com/bandithijo/dmenu-websearch/master/LICENSE[LICENSE^] for details.
